# Generated by Django 4.1.7 on 2023-04-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover_url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
